#!/bin/bash
#
# This script expects 1 environment variable
#   1. SENV_IMAGEROOT - The root of Image Sandbox for Singularity
#
# -- Need to get rid of this in production
export SENV_IMAGEROOT=/glade/u/apps/ch/opt/hpe-cpe/22.02/cray_hpe_cpe_22.02-021622

ALLARGS=" $@ "
NARGS=$#
me=$(whoami)
THESHELL="/bin/bash"

LOGFIL="/glade/scratch/csgteam/logs/cpe/${me}.$(hostname -s).$$"
echo "Started: $(date +'%Y-%m-%dT%H:%M:%S')" > ${LOGFIL}

source /etc/profile.d/modules.sh
ml singularity
SCRDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export SINGULARITY=$(which singularity)
export SCR_IMAGEROOT=${SENV_IMAGEROOT}
export SINGULARITYENV_OMP_NUM_THREADS=$OMP_NUM_THREADS
export STARTUPENV=${SCRDIR}/startupenv
export STARTUPRC=${SCRDIR}/spackenv
export SINGULARITYENV_BASH_ENV=$STARTUPRC

if [ -n "$CRAYENV_GPU_SUPPORT" ]; then
    export GPUARGS="--nv"
else
    export GPUARGS=
fi

export BINDARGS="-B/glade,/var/spool/pbs,/var/run/munge,/glade/u/apps/opt/nvhpc/21.3:/opt/nvidia/hpc_sdk,/glade/u/apps/ch/opt/hpe-cpe/22.02/ncar:/usr/ncar,/glade/u/apps/ch/opt/hpe-cpe/22.02/nvhpc/bin:/opt/cray/pe/mpich/8.1.13/ofi/nvidia/20.7/bin,/opt/pbs,/glade/u/apps/ch/opt/hpe-cpe/22.02/etc/bash.bashrc.local:/etc/bash.bashrc.local"

if [ ! -z "$PBS_JOBID" ] ; then
    export JUST_JOBID=$(echo $PBS_JOBID|awk -F\. '{print $1}')
    DEB_SCRATCH=/glade/scratch/${me}/.palsd/${JUST_JOBID}/var/tmp/$(hostname -s)
    PALSETC=/glade/scratch/${me}/.palsd/${JUST_JOBID}/etc
    if [ ! -d ${PALSETC} ] ; then
       mkdir -p ${PALSETC}
    fi
    if [ ! -d ${DEB_SCRATCH} ] ; then
       mkdir -p ${DEB_SCRATCH}
    fi
    LOC_BINDARGS="${BINDARGS},${DEB_SCRATCH}:/tmp,${DEB_SCRATCH}:/var/run/palsd,${PALSETC}:/etc/pals"
#   ${SCRDIR}/start_slurm.sh < /dev/null
    export DEB_SCRATCH
    export PALSD_LOGFILE="/tmp/palsd.log"
    export PALSD_DEBUG=2
    export PALSD_RUN_DIR="/tmp/palsd"
    PALSPORT=$(( 7919 + $(( $JUST_JOBID % 8192 ))))
    export PALSD_PORT=${PALSPORT}
    export PALS_PORT=${PALSPORT}
    export APRUN_PORT=${PALSPORT}
    export RFE_811452_DISABLE=1
    ${SCRDIR}/start_palsdaemons.sh < /dev/null
else
    DEB_SCRATCH=/glade/scratch/${me}
    LOC_BINDARGS="${BINDARGS},${DEB_SCRATCH}:/tmp"
fi

shargs="--rcfile ${STARTUPRC}"

ml purge

for evar in ${!MODULE*} ${!LMOD*} ${!__LMOD*} ${!LUA*} ${!_ModuleTable*} __Init_Default_Modules; do
    unset $evar
done

unset -f module
unset -f ml

if [ $NARGS -eq 0 ] ; then
   ${SINGULARITY} run -u ${LOC_BINDARGS} ${GPUARGS} --env-file ${STARTUPENV} \
              ${SCR_IMAGEROOT} ${THESHELL} ${shargs}
else
   ${SINGULARITY} run -u ${LOC_BINDARGS} ${GPUARGS} --env-file ${STARTUPENV} \
              ${SCR_IMAGEROOT} ${THESHELL} -c "${ALLARGS}"
fi
echo "Ended: $(date +'%Y-%m-%dT%H:%M:%S')" >> ${LOGFIL}
