#!/bin/bash
#
# This script expects 1 environment variable
#   1. SENV_IMAGEROOT - The root of Image Sandbox for Singularity
#

ALLARGS="$@"
NARGS=$#
me=$(whoami)
BASH="/bin/bash"

LOGFIL="/glade/scratch/csgteam/logs/cpe/${me}.$(hostname -s).$$"
echo "Started: $(date +'%Y-%m-%dT%H:%M:%S')" > ${LOGFIL}

SCRDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export SINGULARITY=$(which singularity)
export SCR_IMAGEROOT=${SENV_IMAGEROOT}
export SINGULARITYENV_OMP_NUM_THREADS=$OMP_NUM_THREADS
export STARTUPENV=${SCRDIR}/startupenv
export STARTUPRC=${SCRDIR}/bashenv
export SINGULARITYENV_BASH_ENV=$STARTUPRC

if [ ! -z "$PBS_JOBID" ] ; then
    SCRATCH=/glade/scratch/${me}/.slurm/${PBS_JOBID}/var/tmp/$(hostname -s)
    if [ ! -d ${SCRATCH} ] ; then
       mkdir -p ${SCRATCH}/d
    fi
    ${SCRDIR}/start_slurm.sh < /dev/null
else
    SCRATCH=/glade/scratch/${me}
fi

shargs="--rcfile ${STARTUPRC}"

source /etc/profile.d/modules.sh
ml purge
unset MODULEPATH_ROOT
unset MODULEPATH
unset MODULESHOME
unset -f module
unset -f ml

if [ $NARGS -eq 0 ] ; then
   ${SINGULARITY} run -u -B/glade,${SCRATCH}:/tmp --env-file ${STARTUPENV} \
              ${SCR_IMAGEROOT} ${BASH} ${shargs}
else
   ${SINGULARITY} run -u -B/glade,${SCRATCH}:/tmp --env-file ${STARTUPENV} \
              ${SCR_IMAGEROOT} ${BASH} -c "${ALLARGS}"
fi
echo "Ended: $(date +'%Y-%m-%dT%H:%M:%S')" >> ${LOGFIL}
